-- Seed 15 Tool Pages for inspir
INSERT INTO seo_tool_pages (tool_id, title, slug, description, long_description, features, use_cases, how_it_works, seo_title, seo_description, seo_keywords, og_image_url) VALUES

('quiz-generator', 'AI Quiz Generator', 'quiz-generator',
 'Create custom quizzes instantly with AI',
 'Generate personalized quizzes on any topic with adjustable difficulty levels. Perfect for test preparation and knowledge assessment.',
 '["Instant quiz generation", "Multiple difficulty levels", "Custom question count", "Various question types", "Immediate feedback"]'::jsonb,
 '["Exam preparation", "Knowledge testing", "Study review", "Self-assessment"]'::jsonb,
 'Simply enter your topic, choose difficulty (easy, medium, hard), select the number of questions, and our AI generates a comprehensive quiz instantly.',
 'AI Quiz Generator | Create Custom Quizzes | inspir',
 'Generate custom quizzes instantly with AI. Multiple difficulty levels, various question types. Perfect for exam prep and study review.',
 ARRAY['quiz generator', 'AI quiz maker', 'test generator', 'study quiz']),

('flashcards', 'AI Flashcards', 'flashcards',
 'Study smarter with AI-powered flashcards',
 'Create and study with intelligent flashcards that adapt to your learning pace. Features spaced repetition for optimal retention.',
 '["AI-generated flashcards", "Spaced repetition algorithm", "Progress tracking", "Flip animations", "Import/export decks"]'::jsonb,
 '["Vocabulary learning", "Formula memorization", "Key concept review", "Language study"]'::jsonb,
 'Enter your study material, and our AI creates optimized flashcards. Study with spaced repetition to maximize long-term retention.',
 'AI Flashcards | Smart Study Cards | inspir',
 'Create AI-powered flashcards with spaced repetition. Perfect for vocabulary, formulas, and concept memorization.',
 ARRAY['flashcards', 'study cards', 'spaced repetition', 'memory cards']),

('study-timer', 'Study Timer', 'study-timer',
 'Pomodoro timer and focus sessions',
 'Boost productivity with customizable study timers. Features Pomodoro technique, break reminders, and session tracking.',
 '["Pomodoro timer (25 min)", "Custom durations", "Break reminders", "Session history", "Focus mode"]'::jsonb,
 '["Focused study sessions", "Time management", "Productivity tracking", "Break scheduling"]'::jsonb,
 'Choose your study duration (15, 25, or 45 minutes), start the timer, and focus completely until the break bell rings.',
 'Study Timer | Pomodoro Timer for Students | inspir',
 'Boost focus with our Pomodoro study timer. Customizable durations, break reminders, and session tracking.',
 ARRAY['study timer', 'pomodoro timer', 'focus timer', 'productivity timer']),

('math-solver', 'AI Math Solver', 'math-solver',
 'Step-by-step math solutions',
 'Get detailed solutions to math problems with step-by-step explanations. Covers algebra, calculus, geometry, and more.',
 '["Step-by-step solutions", "Multiple solution methods", "Equation rendering", "Graph plotting", "Work shown"]'::jsonb,
 '["Homework help", "Exam preparation", "Concept understanding", "Problem checking"]'::jsonb,
 'Enter your math problem, and our AI provides a detailed solution with every step explained clearly.',
 'AI Math Solver | Step-by-Step Math Help | inspir',
 'Get step-by-step math solutions with AI. Covers algebra, calculus, geometry. Detailed explanations for every problem.',
 ARRAY['math solver', 'math help', 'algebra solver', 'calculus help']),

('habit-tracker', 'Study Habit Tracker', 'habit-tracker',
 'Build consistent study habits',
 'Track your daily study habits and build streaks. Visual progress tracking and habit reminders keep you motivated.',
 '["Daily habit checkboxes", "Streak counter", "Progress visualization", "Habit reminders", "Motivational quotes"]'::jsonb,
 '["Building study routine", "Consistency tracking", "Goal achievement", "Motivation"]'::jsonb,
 'Set your study habits, check them off daily, and watch your streaks grow. Visual progress keeps you motivated.',
 'Study Habit Tracker | Build Learning Habits | inspir',
 'Build consistent study habits with daily tracking, streak counters, and progress visualization. Stay motivated.',
 ARRAY['habit tracker', 'study habits', 'habit building', 'streak tracker']),

('image-analysis', 'Image Homework Helper', 'image-analysis',
 'Upload homework photos for instant help',
 'Take a photo of your homework problem and get instant AI-powered explanations and solutions.',
 '["Photo upload", "OCR text recognition", "Handwriting detection", "Instant analysis", "Detailed explanations"]'::jsonb,
 '["Homework help", "Problem solving", "Quick answers", "Understanding concepts"]'::jsonb,
 'Snap a photo of your homework, upload it, and our AI analyzes the problem and provides a detailed explanation.',
 'Image Homework Helper | Photo Problem Solver | inspir',
 'Upload homework photos for instant AI help. OCR recognition, handwriting detection, and detailed explanations.',
 ARRAY['homework help', 'photo solver', 'image recognition', 'OCR homework']),

('practice-tests', 'AI Practice Tests', 'practice-tests',
 'Full-length practice exams',
 'Simulate real exam conditions with AI-generated practice tests. Timed mode, comprehensive scoring, and performance analytics.',
 '["Full-length practice exams", "Timed mode", "Comprehensive scoring", "Performance analytics", "Detailed feedback"]'::jsonb,
 '["Exam simulation", "Test preparation", "Performance tracking", "Weak area identification"]'::jsonb,
 'Select your subject and exam type, take the practice test under timed conditions, and receive detailed performance analytics.',
 'AI Practice Tests | Exam Simulation | inspir',
 'Take full-length AI-generated practice tests. Timed mode, comprehensive scoring, and detailed performance analytics.',
 ARRAY['practice tests', 'mock exams', 'test simulation', 'exam practice']),

('ai-planner', 'AI Study Planner', 'ai-planner',
 'Smart study schedule generator',
 'Let AI create your personalized study schedule based on your goals, deadlines, and available time.',
 '["Automated scheduling", "Deadline management", "Subject rotation", "Time optimization", "Adaptive planning"]'::jsonb,
 '["Exam planning", "Semester organization", "Time management", "Goal tracking"]'::jsonb,
 'Input your subjects, exam dates, and available study time. Our AI generates an optimized study schedule.',
 'AI Study Planner | Smart Study Schedules | inspir',
 'Generate personalized study schedules with AI. Automated planning, deadline management, and time optimization.',
 ARRAY['study planner', 'study schedule', 'AI planner', 'exam planner']),

('goal-setter', 'Academic Goal Tracker', 'goal-setter',
 'Set and track your learning goals',
 'Define academic goals, track progress, and celebrate milestones. SMART goal framework for effective goal setting.',
 '["SMART goal framework", "Progress tracking", "Milestone celebrations", "Deadline reminders", "Achievement badges"]'::jsonb,
 '["Grade targets", "Skill development", "Long-term planning", "Motivation maintenance"]'::jsonb,
 'Set your academic goals using the SMART framework, track progress daily, and celebrate when you achieve milestones.',
 'Academic Goal Tracker | Student Goal Setting | inspir',
 'Set and track academic goals with SMART framework. Progress tracking, milestones, and achievement badges.',
 ARRAY['goal tracker', 'goal setting', 'academic goals', 'student goals']),

('draw-sketch', 'Visual Learning Canvas', 'draw-sketch',
 'Draw diagrams and visual notes',
 'Create visual notes, diagrams, and sketches to enhance learning. Drawing tools with color palette and shape library.',
 '["Drawing tools", "Color palette", "Shape library", "Eraser and undo", "Export options"]'::jsonb,
 '["Visual note-taking", "Diagram creation", "Concept mapping", "Sketching ideas"]'::jsonb,
 'Use drawing tools to create visual notes and diagrams. Choose colors, add shapes, and export your creations.',
 'Visual Learning Canvas | Drawing Tool for Students | inspir',
 'Draw diagrams and visual notes with our canvas tool. Color palette, shapes, and export options for visual learners.',
 ARRAY['drawing tool', 'visual notes', 'diagram maker', 'sketch tool']),

('study-music', 'Study Music Player', 'study-music',
 'Focus-enhancing study playlists',
 'Curated music playlists designed to enhance focus and concentration. Lo-fi beats, classical, nature sounds, and binaural beats.',
 '["Lo-fi beats playlist", "Classical focus music", "Nature sounds", "Binaural beats", "Timer integration"]'::jsonb,
 '["Focus enhancement", "Concentration boost", "Ambient background", "Stress reduction"]'::jsonb,
 'Choose a playlist (lo-fi, classical, nature, or binaural), set your study timer, and let the music enhance your focus.',
 'Study Music Player | Focus Music for Studying | inspir',
 'Listen to curated study music playlists. Lo-fi beats, classical, nature sounds, and binaural beats for focus.',
 ARRAY['study music', 'focus music', 'lofi beats', 'concentration music']),

('science-lab', 'Virtual Science Lab', 'science-lab',
 'Interactive science experiments',
 'Explore chemistry, physics, and biology through interactive virtual experiments. Safe, accessible, and educational.',
 '["Chemistry simulations", "Physics experiments", "Biology visualizations", "Safe environment", "Detailed explanations"]'::jsonb,
 '["Lab practice", "Concept visualization", "Experiment understanding", "Science learning"]'::jsonb,
 'Select an experiment, follow the virtual procedure, observe results, and learn the underlying scientific principles.',
 'Virtual Science Lab | Interactive Experiments | inspir',
 'Explore chemistry, physics, and biology with virtual experiments. Safe, interactive, and educational simulations.',
 ARRAY['virtual lab', 'science experiments', 'chemistry lab', 'physics lab']),

('visual-learning', 'Mind Maps & Diagrams', 'visual-learning',
 'Create mind maps and flowcharts',
 'Build visual representations of concepts with mind maps, flowcharts, and diagrams. Perfect for visual learners.',
 '["Mind map builder", "Flowchart creator", "Diagram templates", "Auto-layout", "Export to image"]'::jsonb,
 '["Concept organization", "Visual memory", "Brainstorming", "Study summaries"]'::jsonb,
 'Start with a central concept, add branches for related ideas, and create beautiful mind maps that help you understand and remember.',
 'Mind Maps & Diagrams | Visual Learning Tools | inspir',
 'Create mind maps, flowcharts, and diagrams for visual learning. Templates, auto-layout, and export options.',
 ARRAY['mind maps', 'visual learning', 'flowcharts', 'concept maps']),

('notes-sync', 'AI Note-Taking', 'notes-sync',
 'Smart note-taking with AI',
 'Take notes with AI assistance. Cornell method, auto-summarization, and cloud sync across devices.',
 '["Cornell note method", "Auto-summarization", "Cloud sync", "Search functionality", "Export formats"]'::jsonb,
 '["Lecture notes", "Study summaries", "Research notes", "Organized learning"]'::jsonb,
 'Take notes during lectures or while studying. AI helps organize, summarize, and sync your notes across all devices.',
 'AI Note-Taking | Sync Your Study Notes | inspir',
 'Smart note-taking with AI assistance. Cornell method, auto-summarization, and cloud sync across devices.',
 ARRAY['note taking', 'study notes', 'cornell notes', 'AI notes']),

('explain-concept', 'AI Concept Explainer', 'explain-concept',
 'Deep explanations for difficult topics',
 'Get comprehensive explanations of complex concepts. Multiple perspectives, analogies, and examples for better understanding.',
 '["Deep explanations", "Multiple perspectives", "Analogies and examples", "Follow-up questions", "Related concepts"]'::jsonb,
 '["Understanding difficult topics", "Concept clarification", "Learning new material", "Exam preparation"]'::jsonb,
 'Ask about any concept, and our AI provides a thorough explanation with analogies, examples, and multiple perspectives.',
 'AI Concept Explainer | Deep Learning Help | inspir',
 'Get deep explanations of difficult concepts with AI. Multiple perspectives, analogies, and examples for better understanding.',
 ARRAY['concept explainer', 'AI tutor', 'deep learning', 'topic explanation'])

ON CONFLICT (tool_id) DO NOTHING;
